create table diagnosis
(
    id        bigint generated by default as identity
        constraint diagnosis_pkey
            primary key,
    name      varchar(255),
    treatment varchar(255),
    user_id   bigint
        constraint fk4httuif3483pbfq4at5223p3p
            references users
);

insert into diagnosis (name, treatment, user_id)
values ('Diagnosis1', 'Treatment1', 2);